In [10]:
from numpy import *
from numpy import diag
from numpy import dot
from numpy import linalg
import math

In [11]:
arr = array([[0,1,1],[math.sqrt(2),2,0],[0,1,1]])
def svd(matrix):
    a, b, c = linalg.svd(arr)
    print(a)
    print(b)
    print(c)
    print("------------")
    Sigma = diag(b)
    B = c.dot(Sigma.dot(c))
    print(a)
    print(B)
    print(c)

In [12]:
svd(arr)

[[-0.40824829  0.57735027 -0.70710678]
 [-0.81649658 -0.57735027  0.        ]
 [-0.40824829  0.57735027  0.70710678]]
[2.82842712e+00 1.41421356e+00 2.37213427e-17]
[[-4.08248290e-01 -8.66025404e-01 -2.88675135e-01]
 [-5.77350269e-01 -4.89172797e-17  8.16496581e-01]
 [-7.07106781e-01  5.00000000e-01 -5.00000000e-01]]
------------
[[-0.40824829  0.57735027 -0.70710678]
 [-0.81649658 -0.57735027  0.        ]
 [-0.40824829  0.57735027  0.70710678]]
[[ 1.1785113   1.         -0.66666667]
 [ 0.66666667  1.41421356  0.47140452]
 [ 0.40824829  1.73205081  1.15470054]]
[[-4.08248290e-01 -8.66025404e-01 -2.88675135e-01]
 [-5.77350269e-01 -4.89172797e-17  8.16496581e-01]
 [-7.07106781e-01  5.00000000e-01 -5.00000000e-01]]
